CREATE DATABASE IF NOT EXISTS gsspd;
USE gsspd;

/*
CREATE TABLE pokemon (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(40) NOT NULL,
    altura DECIMAL(4, 2) UNSIGNED NOT NULL,
    peso DECIMAL(6, 2) UNSIGNED NOT NULL,
    tipo VARCHAR(14) NOT NULL,
    tipo2 VARCHAR(14) NOT NULL,
    preevolucao VARCHAR(40),
    evolucao VARCHAR(40),
    imgsrc VARCHAR(100) NOT NULL
);*/

INSERT INTO pokemon(id, nome, altura, peso, tipo, tipo2, preevolucao, evolucao, imgsrc) VALUES
(1, 'Bulbasaur', 0.7, 6.9, 'Grama', ', Veneno', 'Nenhuma', 'Ivysaur', '/images/pokemon_images/Bulbasaur.png'),
(2, 'Ivysaur', 1.0, 13.0, 'Grama', ', Veneno', 'Bulbasaur', 'Venusaur', '/images/pokemon_images/Ivysaur.png'),
(3, 'Venusaur', 2.0, 100.0, 'Grama', ', Veneno', 'Ivysaur', 'Nenhuma', '/images/pokemon_images/Venusaur.png'),
(4, 'Charmander', 0.6, 8.5, 'Fogo', '', 'Nenhuma', 'Charmeleon', '/images/pokemon_images/Charmander.png'),
(5, 'Charmeleon', 1.1, 19.0, 'Fogo', '', 'Charmander', 'Charizard', '/images/pokemon_images/Charmeleon.png'),
(6, 'Charizard', 1.7, 90.5, 'Fogo', ', Voador', 'Charmeleon', 'Nenhuma', '/images/pokemon_images/Charizard.png'),
(7, 'Squirtle', 0.5, 9.0, 'Água', '', 'Nenhuma', 'Wartortle', '/images/pokemon_images/Squirtle.png'),
(8, 'Wartortle', 1.0, 22.5, 'Água', '', 'Squirtle', 'Blastoise', '/images/pokemon_images/Wartortle.png'),
(9, 'Blastoise', 1.6, 85.5, 'Água', '', 'Wartortle', 'Nenhuma', '/images/pokemon_images/Blastoise.png'),
(10, 'Caterpie', 0.3, 2.9, 'Inseto', '', 'Nenhuma', 'Metapod', '/images/pokemon_images/Caterpie.png'),
(11, 'Metapod', 0.7, 9.9, 'Inseto', '', 'Caterpie', 'Butterfree', '/images/pokemon_images/Metapod.png'),
(12, 'Butterfree', 1.1, 32.0, 'Inseto', ', Voador', 'Metapod', 'Nenhuma', '/images/pokemon_images/Butterfree.png'),
(13, 'Weedle', 0.3, 3.2, 'Inseto', ', Veneno', 'Nenhuma', 'Kakuna', '/images/pokemon_images/Weedle.png'),
(14, 'Kakuna', 0.6, 10.0, 'Inseto', ', Veneno', 'Weedle', 'Beedrill', '/images/pokemon_images/Kakuna.png'),
(15, 'Beedrill', 1.0, 29.5, 'Inseto', ', Veneno', 'Kakuna', 'Nenhuma', '/images/pokemon_images/Beedrill.png'),
(16, 'Pidgey', 0.3, 1.8, 'Normal', ', Voador', 'Nenhuma', 'Pidgeotto', '/images/pokemon_images/Pidgey.png'),
(17, 'Pidgeotto', 1.1, 30.0, 'Normal', ', Voador', 'Pidgey', 'Pidgeot', '/images/pokemon_images/Pidgeotto.png'),
(18, 'Pidgeot', 1.5, 39.5, 'Normal', ', Voador', 'Pidgeotto', 'Nenhuma', '/images/pokemon_images/Pidgeot.png'),
(19, 'Rattata', 0.3, 3.5, 'Normal', '', 'Nenhuma', 'Raticate', '/images/pokemon_images/Rattata.png'),
(20, 'Raticate', 0.7, 18.5, 'Normal', '', 'Rattata', 'Nenhuma', '/images/pokemon_images/Raticate.png'),
(21, 'Spearow', 0.3, 2.0, 'Normal', ', Voador', 'Nenhuma', 'Fearow', '/images/pokemon_images/Spearow.png'),
(22, 'Fearow', 1.2, 38.0, 'Normal', ', Voador', 'Spearow', 'Nenhuma', '/images/pokemon_images/Fearow.png'),
(23, 'Ekans', 2.0, 6.9, 'Veneno', '', 'Nenhuma', 'Arbok', '/images/pokemon_images/Ekans.png'),
(24, 'Arbok', 3.5, 65.0, 'Veneno', '', 'Ekans', 'Nenhuma', '/images/pokemon_images/Arbok.png'),
(25, 'Pikachu', 0.4, 6.0, 'Elétrico', '', 'Pichu', 'Raichu', '/images/pokemon_images/Pikachu.png'),
(26, 'Raichu', 0.8, 30.0, 'Elétrico', '', 'Pikachu', 'Nenhuma', '/images/pokemon_images/Raichu.png'),
(27, 'Sandshrew', 0.6, 12.0, 'Terra', '', 'Nenhuma', 'Sandslash', '/images/pokemon_images/Sandshrew.png'),
(28, 'Sandslash', 1.0, 29.5, 'Terra', '', 'Sandshrew', 'Nenhuma', '/images/pokemon_images/Sandslash.png'),
(29, 'Nidoran♀', 0.4, 7.0, 'Veneno', '', 'Nenhuma', 'Nidorina', '/images/pokemon_images/Nidoran (Female).png'),
(30, 'Nidorina', 0.8, 20.0, 'Veneno', '', 'Nidoran♀', 'Nidoqueen', '/images/pokemon_images/Nidorina.png'),
(31, 'Nidoqueen', 1.3, 60.0, 'Veneno', ', Terra', 'Nidorina', 'Nenhuma', '/images/pokemon_images/Nidoqueen.png'),
(32, 'Nidoran♂', 0.5, 9.0, 'Veneno', '', 'Nenhuma', 'Nidorino', '/images/pokemon_images/Nidoran (Male).png'),
(33, 'Nidorino', 0.9, 19.5, 'Veneno', '', 'Nidoran♂', 'Nidoking', '/images/pokemon_images/Nidorino.png'),
(34, 'Nidoking', 1.4, 62.0, 'Veneno', ', Terra', 'Nidorino', 'Nenhuma', '/images/pokemon_images/Nidoking.png'),
(35, 'Clefairy', 0.6, 7.5, 'Normal', '', 'Cleffa', 'Clefable', '/images/pokemon_images/Clefairy.png'),
(36, 'Clefable', 1.3, 40.0, 'Normal', '', 'Clefairy', 'Nenhuma', '/images/pokemon_images/Clefable.png'),
(37, 'Vulpix', 0.6, 9.9, 'Fogo', '', 'Nenhuma', 'Ninetales', '/images/pokemon_images/Vulpix.png'),
(38, 'Ninetales', 1.1, 19.9, 'Fogo', '', 'Vulpix', 'Nenhuma', '/images/pokemon_images/Ninetales.png'),
(39, 'Jigglypuff', 0.5, 5.5, 'Normal', '', 'Igglybuff', 'Wigglytuff', '/images/pokemon_images/Jigglypuff.png'),
(40, 'Wigglytuff', 1.0, 12.0, 'Normal', '', 'Jigglypuff', 'Nenhuma', '/images/pokemon_images/Wigglytuff.png'), 
(41, 'Zubat', 0.8, 7.5, 'Veneno', ', Voador', 'Nenhuma', 'Golbat', '/images/pokemon_images/Zubat.png'),
(42, 'Golbat', 1.6, 55.0, 'Veneno', ', Voador', 'Zubat', 'Nenhuma', '/images/pokemon_images/Golbat.png'),
(43, 'Oddish', 0.5, 5.4, 'Grama', ', Veneno', 'Nenhuma', 'Gloom', '/images/pokemon_images/Oddish.png'),
(44, 'Gloom', 0.8, 8.6, 'Grama', ', Veneno', 'Oddish', 'Vileplume', '/images/pokemon_images/Gloom.png'),
(45, 'Vileplume', 1.2, 18.6, 'Grama', ', Veneno', 'Gloom', 'Nenhuma', '/images/pokemon_images/Vileplume.png'),
(46, 'Paras', 0.3, 5.4, 'Inseto', ', Grama', 'Nenhuma', 'Parasect', '/images/pokemon_images/Paras.png'),
(47, 'Parasect', 1.0, 29.5, 'Inseto', ', Grama', 'Paras', 'Nenhuma', '/images/pokemon_images/Parasect.png'),
(48, 'Venonat', 1.0, 30.0, 'Inseto', ', Veneno', 'Nenhuma', 'Venomoth', '/images/pokemon_images/Venonat.png'),
(49, 'Venomoth', 1.5, 12.5, 'Inseto', ', Veneno', 'Venonat', 'Nenhuma', '/images/pokemon_images/Venomoth.png'),
(50, 'Diglett', 0.2, 0.8, 'Terra', '', 'Nenhuma', 'Dugtrio', '/images/pokemon_images/Diglett.png'),
(51, 'Dugtrio', 0.7, 33.3, 'Terra', '', 'Diglett', 'Nenhuma', '/images/pokemon_images/Dugtrio.png'),
(52, 'Meowth', 0.4, 4.2, 'Normal', '', 'Nenhuma', 'Persian', '/images/pokemon_images/Meowth.png'),
(53, 'Persian', 1.0, 32.0, 'Normal', '', 'Meowth', 'Nenhuma', '/images/pokemon_images/Persian.png'),
(54, 'Psyduck', 0.8, 19.6, 'Água', '', 'Nenhuma', 'Golduck', '/images/pokemon_images/Psyduck.png'),
(55, 'Golduck', 1.7, 76.6, 'Água', '', 'Psyduck', 'Nenhuma', '/images/pokemon_images/Golduck.png'),
(56, 'Mankey', 0.5, 28.0, 'Lutador', '', 'Nenhuma', 'Primeape', '/images/pokemon_images/Mankey.png'),
(57, 'Primeape', 1.0, 32.0, 'Lutador', '', 'Mankey', 'Nenhuma', '/images/pokemon_images/Primeape.png'),
(58, 'Growlithe', 0.7, 19.0, 'Fogo', '', 'Nenhuma', 'Arcanine', '/images/pokemon_images/Growlithe.png'),
(59, 'Arcanine', 1.9, 155.0, 'Fogo', '', 'Growlithe', 'Nenhuma', '/images/pokemon_images/Arcanine.png'),
(60, 'Poliwag', 0.6, 12.4, 'Água', '', 'Nenhuma', 'Poliwhirl', '/images/pokemon_images/Poliwag.png'),
(61, 'Poliwhirl', 1.0, 20.0, 'Água', '', 'Poliwag', 'Poliwrath', '/images/pokemon_images/Poliwhirl.png'),
(62, 'Poliwrath', 1.3, 54.0, 'Água', ', Lutador', 'Poliwhirl', 'Nenhuma', '/images/pokemon_images/Poliwrath.png'),
(63, 'Abra', 0.9, 19.5, 'Psíquico', '', 'Nenhuma', 'Kadabra', '/images/pokemon_images/Abra.png'),
(64, 'Kadabra', 1.3, 56.5, 'Psíquico', '', 'Abra', 'Alakazam', '/images/pokemon_images/Kadabra.png'),
(65, 'Alakazam', 1.5, 48.0, 'Psíquico', '', 'Kadabra', 'Nenhuma', '/images/pokemon_images/Alakazam.png'),
(66, 'Machop', 0.8, 19.5, 'Lutador', '', 'Nenhuma', 'Machoke', '/images/pokemon_images/Machop.png'),
(67, 'Machoke', 1.5, 70.5, 'Lutador', '', 'Machop', 'Machamp', '/images/pokemon_images/Machoke.png'),
(68, 'Machamp', 1.6, 130.0, 'Lutador', '', 'Machoke', 'Nenhuma', '/images/pokemon_images/Machamp.png'),
(69, 'Bellsprout', 0.7, 4.0, 'Grama', ', Veneno', 'Nenhuma', 'Weepinbell', '/images/pokemon_images/Bellsprout.png'),
(70, 'Weepinbell', 1.0, 6.4, 'Grama', ', Veneno', 'Bellsprout', 'Victreebel', '/images/pokemon_images/Weepinbell.png'),
(71, 'Victreebel', 1.7, 15.5, 'Grama', ', Veneno', 'Weepinbell', 'Nenhuma', '/images/pokemon_images/Victreebel.png'),
(72, 'Tentacool', 0.9, 45.5, 'Água', ', Veneno', 'Nenhuma', 'Tentacruel', '/images/pokemon_images/Tentacool.png'),
(73, 'Tentacruel', 1.6, 55.0, 'Água', ', Veneno', 'Tentacool', 'Nenhuma', '/images/pokemon_images/Tentacruel.png'),
(74, 'Geodude', 0.4, 20.0, 'Pedra', ', Terra', 'Nenhuma', 'Graveler', '/images/pokemon_images/Geodude.png'),
(75, 'Graveler', 1.0, 105.0, 'Pedra', ', Terra', 'Geodude', 'Golem', '/images/pokemon_images/Graveler.png'),
(76, 'Golem', 1.4, 300.0, 'Pedra', ', Terra', 'Graveler', 'Nenhuma', '/images/pokemon_images/Golem.png'),
(77, 'Ponyta', 1.0, 30.0, 'Fogo', '', 'Nenhuma', 'Rapidash', '/images/pokemon_images/Ponyta.png'),
(78, 'Rapidash', 1.7, 95.0, 'Fogo', '', 'Ponyta', 'Nenhuma', '/images/pokemon_images/Rapidash.png'),
(79, 'Slowpoke', 1.2, 36.0, 'Água', ', Psíquico', 'Nenhuma', 'Slowbro', '/images/pokemon_images/Slowpoke.png'),
(80, 'Slowbro', 1.6, 78.5, 'Água', ', Psíquico', 'Slowpoke', 'Nenhuma', '/images/pokemon_images/Slowbro.png'),
(81, 'Magnemite', 0.3, 6.0, 'Elétrico', '', 'Nenhuma', 'Magneton', '/images/pokemon_images/Magnemite.png'),
(82, 'Magneton', 1.0, 60.0, 'Elétrico', '', 'Magnemite', 'Nenhuma', '/images/pokemon_images/Magneton.png'),
(83, 'Farfetch’d', 0.8, 15.0, 'Normal', ', Voador', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Farfetchd.png'),
(84, 'Doduo', 1.4, 39.2, 'Normal', ', Voador', 'Nenhuma', 'Dodrio', '/images/pokemon_images/Doduo.png'),
(85, 'Dodrio', 1.8, 85.2, 'Normal', ', Voador', 'Doduo', 'Nenhuma', '/images/pokemon_images/Dodrio.png'),
(86, 'Seel', 1.1, 90.0, 'Água', '', 'Nenhuma', 'Dewgong', '/images/pokemon_images/Seel.png'),
(87, 'Dewgong', 1.7, 120.0, 'Água', ', Gelo', 'Seel', 'Nenhuma', '/images/pokemon_images/Dewgong.png'),
(88, 'Grimer', 0.9, 30.0, 'Veneno', '', 'Nenhuma', 'Muk', '/images/pokemon_images/Grimer.png'),
(89, 'Muk', 1.2, 30.0, 'Veneno', '', 'Grimer', 'Nenhuma', '/images/pokemon_images/Muk.png'),
(90, 'Shellder', 0.3, 4.0, 'Água', '', 'Nenhuma', 'Cloyster', '/images/pokemon_images/Shellder.png'),
(91, 'Cloyster', 1.5, 132.5, 'Água', ', Gelo', 'Shellder', 'Nenhuma', '/images/pokemon_images/Cloyster.png'),
(92, 'Gastly', 1.3, 0.1, 'Fantasma', ', Veneno', 'Nenhuma', 'Haunter', '/images/pokemon_images/Gastly.png'),
(93, 'Haunter', 1.6, 0.1, 'Fantasma', ', Veneno', 'Gastly', 'Gengar', '/images/pokemon_images/Haunter.png'),
(94, 'Gengar', 1.5, 40.5, 'Fantasma', ', Veneno', 'Haunter', 'Nenhuma', '/images/pokemon_images/Gengar.png'),
(95, 'Onix', 8.8, 210.0, 'Terra', ', Pedra', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Onix.png'),
(96, 'Drowzee', 1.0, 32.4, 'Psíquico', '', 'Nenhuma', 'Hypno', '/images/pokemon_images/Drowzee.png'),
(97, 'Hypno', 1.6, 75.6, 'Psíquico', '', 'Drowzee', 'Nenhuma', '/images/pokemon_images/Hypno.png'),
(98, 'Krabby', 0.4, 6.5, 'Água', '', 'Nenhuma', 'Kingler', '/images/pokemon_images/Krabby.png'),
(99, 'Kingler', 1.3, 60.0, 'Água', '', 'Krabby', 'Nenhuma', '/images/pokemon_images/Kingler.png'),
(100, 'Voltorb', 0.5, 10.4, 'Elétrico', '', 'Nenhuma', 'Electrode', '/images/pokemon_images/Voltorb.png'),
(101, 'Electrode', 1.2, 66.6, 'Elétrico', '', 'Voltorb', 'Nenhuma', '/images/pokemon_images/Electrode.png'),
(102, 'Exeggcute', 0.4, 2.5, 'Grama', ', Psíquico', 'Nenhuma', 'Exeggutor', '/images/pokemon_images/Exeggcute.png'),
(103, 'Exeggutor', 2.0, 120.0, 'Grama', ', Psíquico', 'Exeggcute', 'Nenhuma', '/images/pokemon_images/Exeggutor.png'),
(104, 'Cubone', 0.4, 6.5, 'Terra', '', 'Nenhuma', 'Marowak', '/images/pokemon_images/Cubone.png'),
(105, 'Marowak', 1.0, 45.0, 'Terra', '', 'Cubone', 'Nenhuma', '/images/pokemon_images/Marowak.png'),
(106, 'Hitmonlee', 1.5, 49.8, 'Lutador', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Hitmonlee.png'),
(107, 'Hitmonchan', 1.4, 50.2, 'Lutador', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Hitmonchan.png'),
(108, 'Lickitung', 1.2, 65.5, 'Normal', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Lickitung.png'),
(109, 'Koffing', 0.6, 1.0, 'Veneno', '', 'Nenhuma', 'Weezing', '/images/pokemon_images/Koffing.png'),
(110, 'Weezing', 1.2, 9.5, 'Veneno', '', 'Koffing', 'Nenhuma', '/images/pokemon_images/Weezing.png'),
(111, 'Rhyhorn', 1.0, 115.0, 'Terra', ', Pedra', 'Nenhuma', 'Rhydon', '/images/pokemon_images/Rhyhorn.png'),
(112, 'Rhydon', 1.9, 120.0, 'Terra', ', Pedra', 'Rhyhorn', 'Nenhuma', '/images/pokemon_images/Rhydon.png'),
(113, 'Chansey', 1.1, 34.6, 'Normal', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Chansey.png'),
(114, 'Tangela', 1.0, 35.0, 'Grama', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Tangela.png'),
(115, 'Kangaskhan', 2.2, 80.0, 'Normal', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Kangaskhan.png'),
(116, 'Horsea', 0.4, 8.0, 'Água', '', 'Nenhuma', 'Seadra', '/images/pokemon_images/Horsea.png'),
(117, 'Seadra', 1.2, 25.0, 'Água', '', 'Horsea', 'Nenhuma', '/images/pokemon_images/Seadra.png'),
(118, 'Goldeen', 0.6, 15.0, 'Água', '', 'Nenhuma', 'Seaking', '/images/pokemon_images/Goldeen.png'),
(119, 'Seaking', 1.3, 39.0, 'Água', '', 'Goldeen', 'Nenhuma', '/images/pokemon_images/Seaking.png'),
(120, 'Staryu', 0.8, 34.5, 'Água', '', 'Nenhuma', 'Starmie', '/images/pokemon_images/Staryu.png'),
(121, 'Starmie', 1.1, 80.0, 'Água', ', Gelo', 'Staryu', 'Nenhuma', '/images/pokemon_images/Starmie.png'),
(122, 'Mr. Mime', 1.3, 54.5, 'Gelo', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Mr mime.png'),
(123, 'Scyther', 1.5, 56.0, 'Inseto', ', Voador', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Scyther.png'),
(124, 'Jynx', 1.4, 40.6, 'Gelo', ', Psíquico', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Jynx.png'),
(125, 'Electabuzz', 1.1, 30.0, 'Elétrico', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Electabuzz.png'),
(126, 'Magmar', 1.3, 44.5, 'Fogo', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Magmar.png'),
(127, 'Pinsir', 1.5, 55.0, 'Inseto', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Pinsir.png'),
(128, 'Tauros', 1.4, 88.4, 'Normal', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Tauros.png'),
(129, 'Magikarp', 0.9, 10.0, 'Água', '', 'Nenhuma', 'Gyarados', '/images/pokemon_images/Magikarp.png'),
(130, 'Gyarados', 6.5, 235.0, 'Água', ', Voador', 'Magikarp', 'Nenhuma', '/images/pokemon_images/Gyarados.png'),
(131, 'Lapras', 2.5, 220.0, 'Água', ', Gelo', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Lapras.png'),
(132, 'Ditto', 0.3, 4.0, 'Normal', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Ditto.png'),
(133, 'Eevee', 0.3, 6.5, 'Normal', '', 'Nenhuma', 'Vaporeon, Jolteon, Flareon', '/images/pokemon_images/Eevee.png'),
(134, 'Vaporeon', 1.0, 29.0, 'Água', '', 'Eevee', 'Nenhuma', '/images/pokemon_images/Vaporeon.png'),
(135, 'Jolteon', 0.8, 24.5, 'Elétrico', '', 'Eevee', 'Nenhuma', '/images/pokemon_images/Jolteon.png'),
(136, 'Flareon', 0.9, 25.0, 'Fogo', '', 'Eevee', 'Nenhuma', '/images/pokemon_images/Flareon.png'),
(137, 'Porygon', 0.8, 36.5, 'Normal', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Porygon.png'),
(138, 'Omanyte', 0.4, 7.5, 'Água', ', Pedra', 'Nenhuma', 'Omastar', '/images/pokemon_images/Omanyte.png'),
(139, 'Omastar', 1.0, 35.0, 'Água', ', Pedra', 'Omanyte', 'Nenhuma', '/images/pokemon_images/Omastar.png'),
(140, 'Kabuto', 0.5, 11.5, 'Água', ', Pedra', 'Nenhuma', 'Kabutops', '/images/pokemon_images/Kabuto.png'),
(141, 'Kabutops', 1.3, 40.5, 'Água', ', Pedra', 'Kabuto', 'Nenhuma', '/images/pokemon_images/Kabutops.png'),
(142, 'Aerodactyl', 1.8, 59.0, 'Pedra', ', Voador', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Aerodactyl.png'),
(143, 'Snorlax', 2.1, 460.0, 'Normal', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Snorlax.png'),
(144, 'Articuno', 1.7, 55.4, 'Gelo', ', Voador', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Articuno.png'),
(145, 'Zapdos', 1.6, 52.6, 'Elétrico', ', Voador', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Zapdos.png'),
(146, 'Moltres', 2.0, 60.0, 'Fogo', ', Voador', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Moltres.png'),
(147, 'Dratini', 1.8, 3.3, 'Dragão', '', 'Nenhuma', 'Dragonair', '/images/pokemon_images/Dratini.png'),
(148, 'Dragonair', 4.0, 16.5, 'Dragão', '', 'Dratini', 'Dragonite', '/images/pokemon_images/Dragonair.png'),
(149, 'Dragonite', 2.2, 210.0, 'Dragão', ', Voador', 'Dragonair', 'Nenhuma', '/images/pokemon_images/Dragonite.png'),
(150, 'Mewtwo', 2.0, 122.0, 'Psíquico', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Mewtwo.png'),
(151, 'Mew', 0.4, 4.0, 'Psíquico', '', 'Nenhuma', 'Nenhuma', '/images/pokemon_images/Mew.png');